
aCam[0]:
  Full_W: 2592
  Full_H: 1944
  Full_FOV: 78
  #Image_Zoom:	1.05		1.125		1.2
  Image_Zoom: 1
  #Image_W: 1920
  #Image_H: 1080
  #Image_Zoom: 1.8
  #Image_W: 1280
  #Image_H: 720
  #Exposure: 400
  #Image_W: 2048
  #Image_H: 1536
  Image_FOV: 83
  #Image_FOV_W: 0.872753
  #Image_FOV_H: 0.523095
  Proj_W: 4
  Proj_H: 3
  Proj_N: 1
  Proj_F: 100
  #
  Proj_L: -1
  Proj_R: 1
  Proj_B: -1
  Proj_T: 1
  #
  T:
    x: 0
    y: 0
    z: 0
  R:
    x: 0
    y: 0
    z: 0
  Exposure: 500
  Focus: 187	#187 204
  #Focus:	130	120	80	0	-1
  #Exposure:	200	400	600	800
  Zoom: 5

aCam[1]:
  T:
    x: 0.001723
    y: -3.886186
    z: 0.0
  R:
    x: -1.785241
    y: -0.115888
    z: -0.055034
  #Exposure: 400
  Focus: 153
  Zoom: 5


Eye_Line_Ray: 0
Eye_GlintMode: 0
GazeAvg: 0

GazeMode: 0
Pointer_Mode: 1

Screen:
  W: 8
  H: 5
  C:
    x: 0
    y: 0
    z: 60


Screen_N: 3
aScreen[0]:
  PixW: 1280
  PixH: 1024
  Off:
    x: 1200
    y: 896

aScreen[1]:
  PixW: 1200
  PixH: 1920
  Off:
    x: 0
    y: 0

aScreen[2]:
  PixW: 1280
  PixH: 1024
  Off:
    x: 2480
    y: 896


tmp:
  scale: 6
  x: 2
  y: 0
  z: -8

aDbg[0]:
  Scale: 0.2
  R_X: 0
  R_Y: 180
  Off:
    x: 1000
    y: 500
aDbg[1]:
  Scale: 0.2
  T_X: 0
  T_Y: 0
  R_X: 90
  R_Y: 180
  Off:
    x: 1000
    y: 200
aDbg[2]:
  Scale: 0.2
  #T_X: 15
  T_Y: 0
  R_X: 0
  R_Y: 90
  Off:
    x: 1200
    y: 200

Y_Level: 128
DeSat: 0

aLight[0]:
  P:
    x: -4.5
    y: 0
    z: 0
aLight[1]:
  P:
    x: 4.5
    y: 0
    z: 0

Head:
  Type: Head_Type_ePoint
  Mod:	#brick size x,z 0.8,  y full 0.96  flat 0.32
    PC:
      x: 0.0
      y: -1.6
      z: 3.2
    #PC:
      #x: 0.0
      #y: -3
      #z: 3.2
    PL:
      x: -9.6
      y: -0.96
      z: -0.8
    PR:
      x: 9.6
      y: -0.96
      z: -0.8
    TInc:
      x: 0.01
      y: 0.01
      z: 0.01
    RInc:
      x: 0.1
      y: 0.3
      z: 0.3
  
  DotC:
    Ax: 20
    Ay: 20
    Aa: 0
    Exp_R: 70
    Min_R: 10
    Max_R: 70
    
    Pix_Bright: 50
    S4_Pix_Bright: 20
    AngRes: 2.0
    S5:
      Min_N: 70
      Min_R: 0
      Break_Dist: 5
      Pix_Bright: 50
      Pix_Dark: 30
      Diff_Dist: 10
      Pix_Diff_Start: 20
      Pix_Diff_Min: 2
    aCam[0]:
      FF:
        Max_R: 128
        Perf_R: 25
        MaxDiff_R: 0.4
        Search_R: 200
        Y: 60
        Y_Marg: 40
        GY: 240
    
    #Fit: eEye_Fit_S0	eEye_Fit_S3Fit_Eye	eEye_Fit_S3Fit_Point	eEye_Fit_S5_START		eEye_Fit_FF_START		eEye_Fit_FF_Diode
    Fit: eEye_Fit_FF_START
    PFit: eEye_PFit_S2
    Fit_Scale: 0.2
    Fit_Trans: 0.2
    S2Fit_Scale: 0.8
    S2Fit_Trans: 0.7
    
    LinView:
      x: 0
      y: 0
  
  DotL:
    LinView:
      x: 800
      y: 300
    CirView:
      x: 00
      y: 00
  
  DotR:
    LinView:
      x: 0
      y: 0
  SRX: 0.0
  SRY: 0.0
  

Left:
  Ax: 60
  Ay: 60
  Aa: 0
#  Aa: M_PI/4
  
  AngRes: 1.0
  Exp_R: 50
  Min_R: 20
  Max_R: 80

  Pix_Bright: 20
  S4_Pix_Bright: 60
  S5:
    Min_N: 90
    Min_R: 30
    Break_Dist: 5
    Pix_Bright: 16
    Pix_Dark: 10
    Diff_Dist: 10
    Pix_Diff_Start: 30
    Pix_Diff_Min: 5
    
  aCam[0]:
    FF:
      Max_R: 64
      Perf_R: 15
      MaxDiff_R: 0.2f
      Search_R: 80
      Y: 60
      Y_Marg: 10
      GY: 150
      GSearch_R: 60
  
  PFit_R: 40
  
  Fit: eEye_Fit_FF_START
# Fit: eEye_Fit_S3Fit_Eye	eEye_Fit_S4Fit_Edge0	eEye_Fit_S4Fit_Edge1	eEye_Fit_S4Fit_Edge2	eEye_Fit_S5_START		eEye_Fit_S5_Diff		eEye_Fit_FF_START		eEye_Fit_C
  PFit: eEye_PFit_S3
# PFit: eEye_PFit_S1	eEye_PFit_S2	eEye_PFit_S3	eEye_PFit_S3const	eEye_PFit_RANSAC
  Fit_Scale: 0.1
  Fit_Trans: 0.1
  S2Fit_Scale: 0.8
  S2Fit_Trans: 0.7
  
  GTF:
    x: 0.0001
    y: 0.0
  
  LR: 0.393
  
  InHead:
    #R: 0.85
    R: 1.25
    P:
      x: -3.246802
      y: 0.074058
      z: -1.615316

  LinView:
    x: 00
    y: 0
  CirView:
    x: 800
    y: 0

Right:
  Ax: 60
  Ay: 60
  Aa: 0
  
  AngRes: 1.0
  Exp_R: 50
  Min_R: 20
  Max_R: 80

  Pix_Bright: 5
  S4_Pix_Bright: 60
  S5:
    Min_N: 90
    Min_R: 30
    Break_Dist: 5
    Pix_Bright: 20
    Pix_Dark: 10
    Diff_Dist: 10
    Pix_Diff_Start: 30
    Pix_Diff_Min: 5
  
  aCam[0]:
    FF:
      Max_R: 256
      Perf_R: 18
      MaxDiff_R: 0.2f
      Search_R: 80
      Y: 60
      Y_Marg: 10
      GY: 150
      GSearch_R: 60
  
  PFit_R: 100
  
  Fit: eEye_Fit_FF_START
  PFit: eEye_PFit_S3
  
  Fit_Scale: 0.1
  Fit_Trans: 0.1
  S2Fit_Scale: 0.8
  S2Fit_Trans: 0.7
  
  GTF:
    x: 0.0
    y: 0.0
  
  LR: 0.393
  
  InHead:
    #R: 0.85
    R: 1.25
    P:
      x: 3.405655
      y: 0.249110
      z: -1.469640

  LinView:
    x: 0
    y: 0

bEye_S4_EdgeMark3_Micro: 0
bHead_Eye_LineDraw: 1

GazeAvg_3_MinAlpha: 0.0
GazeAvg_3_MinDist: 1
GazeAvg_3_Dist: 80
Micro:
  SX: -400.0
  SY: 1000.0



Action:
  GazeHold: 57		Space
  Mode_Switch: 15		Tab
  
  Head_Point_Train: 0x14	t
  
  EyeCent_CalNext: 43	BackSlash
  Back: 14			BackSpace
  
  EyeCent_Inc:	78	KP +
  EyeCent_Dec:	74	KP -
  
  CalNext: 28		Enter
  
  Cam_TCal: 10		9
  Cam_RCal: 11		0
  
  Head_Snap: 40		-
  
  ReThr: 24			o
  
  Screen_Hide: 41		`
  Screen0: 2		1
  Screen1: 3
  Screen2: 4
  
  Screen_Left: 105	left arrow
  Screen_Right: 106
  Screen_Down: 108
  Screen_Up: 103
  
  Screen_Point: 107	end
  Screen_PointDel: 111	del
  
  View_Zoom: 53		slash
  Head_Eye_LineDraw: 52	dot
  
  Micro_Tog: 34		g
  
