
Cam:
  Full_W: 2592
  Full_H: 1944
  Full_FOV: 83
  Image_Zoom: 1.3
  #Image_Zoom:	3	2.2	1.9	1.3	1
  Image_W: 1920
  Image_H: 1080
  #Image_W: 2048
  #Image_H: 1536
#  Image_FOV: 83
  Focus: 0
  #Focus:	130	120	80	0	-1
  Exposure: 400
  #Exposure:	200	400	600	800
  Zoom: 1

View_W: 1920
View_H: 1080
#View_W: 2048
#View_H: 1536

Proj_W: 4
Proj_H: 3
Proj_N: 1
Proj_F: 100

Proj_L: -1
Proj_R: 1
Proj_B: -1
Proj_T: 1

Eye_Line_Ray: 0
GazeAvg: 0

Pointer_Mode: 1

Screen:
  W: 8
  H: 5
  C:
    x: 0
    y: 0
    z: 10


Screen_N: 3
aScreen[0]:
  PixW: 1280
  PixH: 1024
  Off:
    x: 1200
    y: 896

aScreen[1]:
  PixW: 1200
  PixH: 1920
  Off:
    x: 0
    y: 0

aScreen[2]:
  PixW: 1280
  PixH: 1024
  Off:
    x: 2480
    y: 896


tmp:
  x: 12
  y: 5
  z: 1

Y_Level: 128
DeSat: 0

Head:
  Mod:
    #PC:
      #x: 0
      #y: -1
      #z: 3.0
    #PL:
      #x: -7.5
      #y: 0
      #z: 0
    #PR:
      #x: 7.5
      #y: 0
      #z: 0
    PC:
      x: 0
      y: -1.0
      z: 3.0
    PL:
      x: -7.5
      y: 2.0
      z: 0
    PR:
      x: 7.5
      y: 2.0
      z: 0
    #PC:
      #x: 0
      #y: -1.5
      #z: 0.0
    #PL:
      #x: -2.5
      #y: 0
      #z: 0
    #PR:
      #x: 2.5
      #y: 0
      #z: 0
    TInc:
      x: 0.01
      y: 0.01
      z: 0.01
    RInc:
      x: 0.1
      y: 0.3
      z: 0.3
  
  DotC:
    Ax: 20
    Ay: 20
    Aa: 0
    Exp_R: 70
    Min_R: 10
    Max_R: 70
    
    S4_Pix_Bright: 80
    AngRes: 3.0
    S5:
      Min_N: 70
      Min_R: 0
      Pix_Bright: 220
      Pix_Dark: 200
      Diff_Dist: 10
      Pix_Diff_Start: 20
      Pix_Diff_Min: 2
    
    #Fit: eEye_Fit_S0
    Fit: eEye_Fit_S5_START
    PFit: eEye_PFit_S2
    Fit_Scale: 0.2
    Fit_Trans: 0.2
    S2Fit_Scale: 0.8
    S2Fit_Trans: 0.7
    
    LinView:
      x: 0
      y: 0
  
  DotL:
    LinView:
      x: 800
      y: 300
  
  DotR:
    LinView:
      x: 0
      y: 0
  

Left:
  Ax: 60
  Ay: 60
  Aa: 0
#  Aa: M_PI/4
  
  AngRes: 1.0
  Exp_R: 50
  Min_R: 80
  Max_R: 120

  Pix_Bright: 60
  S4_Pix_Bright: 60
  S5:
    Min_N: 150
    Min_R: 30
    Pix_Bright: 120
    Pix_Dark: 100
    Diff_Dist: 10
    Pix_Diff_Start: 30
    Pix_Diff_Min: 5
  
  PFit_R: 100
  
  Fit: eEye_Fit_S5_START
# Fit: eEye_Fit_S3Fit_Eye	eEye_Fit_S4Fit_Edge0	eEye_Fit_S4Fit_Edge1	eEye_Fit_S4Fit_Edge2	eEye_Fit_S5_START		eEye_Fit_S5_Diff	eEye_Fit_C
  PFit: eEye_PFit_S3const
# PFit: eEye_PFit_S1	eEye_PFit_S2	eEye_PFit_S3	eEye_PFit_S3const	eEye_PFit_RANSAC
  Fit_Scale: 0.1
  Fit_Trans: 0.1
  S2Fit_Scale: 0.8
  S2Fit_Trans: 0.7
  
  InHead:
    R: 1.2
    P:
      #x: -3.308714
      #y: 0.000961
      #z: 0.001262
      x: -3.151785
      y: 0.527396
      z: -0.008276

  LinView:
    x: 800
    y: 0

Right:
  Ax: 60
  Ay: 60
  Aa: 0
  
  AngRes: 1.0
  Exp_R: 50
  Min_R: 80
  Max_R: 120

  Pix_Bright: 60
  S4_Pix_Bright: 60
  S5:
    Min_N: 90
    Min_R: 0
    Pix_Bright: 110
    Pix_Dark: 90
    Diff_Dist: 10
    Pix_Diff_Start: 30
    Pix_Diff_Min: 5
  
  PFit_R: 100
  
  Fit: eEye_Fit_S5_START
  PFit: eEye_PFit_S3const
  
  Fit_Scale: 0.1
  Fit_Trans: 0.1
  S2Fit_Scale: 0.8
  S2Fit_Trans: 0.7
  
  InHead:
    R: 1.2
    P:
      #x: 3.332723
      #y: 0.124271
      #z: 0.002492
      x: 3.115145
      y: 0.821904
      z: -0.008704

  LinView:
    x: 0
    y: 0

bEye_S4_EdgeMark3_Micro: 0
bHead_Eye_LineDraw: 1


Micro:
  SX: -200.0
  SY: 150.0



Action:
  Mod_Key: 66
  GazeHold: 0x20
  Mode_Switch: 0xff09
  EyeCent_CalNext: 0x5c
  CalNext: 0xff0d
  Back: 0xff08
  Screen0: 0x27
  Screen1: 0x2c
  Screen2: 0x2e
  Screen_Left: 0xff51
  Screen_Right: 0xff53
  Screen_Down: 0xff54
  Screen_Up: 0xff52
  Screen_TL: 79
  Screen_TC: 80
  Screen_TR: 81
  Screen_ML: 83
  Screen_MC: 84
  Screen_MR: 85
  Screen_BL: 87
  Screen_BC: 88
  Screen_BR: 89
  View_Zoom: 0x69
  Head_Eye_LineDraw: 0x30
  Micro_Tog: 0xffc5

Action:
  Mod_Key: 66
  GazeHold: 65
  Mode_Switch: 23
  EyeCent_CalNext: 51
  CalNext: 36
  Back: 22
  Screen0: 24
  Screen1: 25
  Screen2: 26
  Screen_Left: 113
  Screen_Right: 114
  Screen_Down: 116
  Screen_Up: 111
  Screen_TL: 79
  Screen_TC: 80
  Screen_TR: 81
  Screen_ML: 83
  Screen_MC: 84
  Screen_MR: 85
  Screen_BL: 87
  Screen_BC: 88
  Screen_BR: 89
  View_Zoom: 49
  Head_Eye_LineDraw: 19
;j
